name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04-arm]
        java: ['17', '21']
      fail-fast: false
    name: Temurin ${{ matrix.java }} (${{ matrix.os }})
    steps:
    - uses: actions/checkout@v7

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v6
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Run all tests
      run: mvn -B -Ptests-for-ci,publication clean package --file pom.xml
      env:
        TZ: UTC

    - name: Upload coverage to Codecov
      if: matrix.java == '17' && matrix.os == 'ubuntu-22.04'
      uses: codecov/codecov-action@v7
      with:
        files: db-scheduler/target/site/jacoco/jacoco.xml
        flags: db-scheduler
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    timeout-minutes: 150
